# core/skill_factory.py — JARVIS SKILL AUTO-GENERATOR
# ──────────────────────────────────────────────────────────────────────────────
# Reads error logs and unresolved command patterns, then uses Ollama to
# auto-generate new skill modules and hot-loads them into the plugin manager.
#
# Trigger (automatic): Every AGENT_FAIL logged in memory/agent_failures.jsonl
# Trigger (manual):    skill_factory.generate_skill("play netflix on tv")
#
# Generated skills are saved to skills/auto_<slug>.py and immediately loaded
# into the live plugin manager — no restart required.
# ──────────────────────────────────────────────────────────────────────────────

from __future__ import annotations

import os, json, re, datetime, hashlib, logging, textwrap
import requests

log = logging.getLogger("skill_factory")

OLLAMA_URL      = "http://localhost:11434/api/chat"
FACTORY_MODEL   = "qwen2.5-coder:7b"   # good at Python codegen
SKILLS_DIR      = "skills"
FAILURES_LOG    = os.path.join("memory", "agent_failures.jsonl")
GENERATED_LOG   = os.path.join("memory", "auto_skills.json")
MAX_RETRIES     = 2
SKILL_TEMPLATE  = '''# skills/auto_{slug}.py  —  AUTO-GENERATED by SkillFactory
# Created: {ts}  |  Trigger: "{trigger}"
SKILL_NAME  = "{name}"
TRIGGERS    = {triggers}
DESCRIPTION = "{description}"

def run(command: str, context: dict) -> str:
{body}
'''


class SkillFactory:
    """
    Watches for unresolved commands and uses an LLM to write new skill modules.
    Integrates with PluginManager for zero-downtime hot-loading.
    """

    def __init__(self):
        os.makedirs(SKILLS_DIR, exist_ok=True)
        os.makedirs("memory",   exist_ok=True)

    # ─────────────────────────────────────────────────────────────────────────
    # Public API
    # ─────────────────────────────────────────────────────────────────────────

    def log_failure(self, command: str, error: str = "", context: dict | None = None):
        """
        Record a command that JARVIS could not handle.
        Called by jarvis_brain.py when process() returns a failure/fallback.
        """
        entry = {
            "ts":      datetime.datetime.now().isoformat(),
            "command": command,
            "error":   str(error)[:300],
            "context": context or {},
        }
        try:
            with open(FAILURES_LOG, "a", encoding="utf-8") as f:
                f.write(json.dumps(entry) + "\n")
        except Exception as e:
            log.warning(f"[SkillFactory] Could not write failure log: {e}")

    def get_recent_failures(self, n: int = 20) -> list[dict]:
        """Return the N most recent unresolved command failures."""
        if not os.path.exists(FAILURES_LOG):
            return []
        lines = []
        try:
            with open(FAILURES_LOG, "r", encoding="utf-8") as f:
                lines = f.readlines()
        except Exception:
            return []
        records = []
        for line in reversed(lines):
            try:
                records.append(json.loads(line.strip()))
            except Exception:
                pass
            if len(records) >= n:
                break
        return records

    def generate_skill(self, trigger_command: str, context: str = "") -> str:
        """
        Ask the LLM to write a new skill for the given command.
        Returns the path to the generated skill file, or an error string.
        """
        slug = self._slugify(trigger_command)

        # Avoid regenerating the same skill twice
        if self._already_generated(slug):
            return f"[SkillFactory] Skill for '{trigger_command}' already exists."

        print(f"[SkillFactory] Generating skill for: '{trigger_command}'")

        for attempt in range(1, MAX_RETRIES + 1):
            skill_code = self._call_llm(trigger_command, context, attempt)
            if not skill_code:
                continue

            # Validate the generated code parses
            try:
                compile(skill_code, "<generated>", "exec")
            except SyntaxError as e:
                print(f"[SkillFactory] Attempt {attempt} syntax error: {e}")
                continue

            # Write to skills/
            path = os.path.join(SKILLS_DIR, f"auto_{slug}.py")
            try:
                with open(path, "w", encoding="utf-8") as f:
                    f.write(skill_code)
            except Exception as e:
                return f"[SkillFactory] Write error: {e}"

            # Hot-load into the plugin manager
            self._hot_load(path)
            self._record_generated(slug, trigger_command, path)
            print(f"[SkillFactory] ✅ Skill saved and hot-loaded: {path}")
            return path

        return f"[SkillFactory] Could not generate a valid skill after {MAX_RETRIES} attempts."

    def auto_heal_failures(self, max_skills: int = 3) -> list[str]:
        """
        Scan recent failures and auto-generate skills for unresolved patterns.
        Called periodically by the ProactiveEngine or manually.
        Returns list of generated skill paths.
        """
        failures = self.get_recent_failures(20)
        generated = []
        seen: set[str] = set()

        for f in failures:
            cmd = f.get("command", "").strip()
            if not cmd or self._slugify(cmd) in seen:
                continue
            seen.add(self._slugify(cmd))
            err = f.get("error", "")
            result = self.generate_skill(cmd, context=err)
            if result.endswith(".py"):
                generated.append(result)
            if len(generated) >= max_skills:
                break

        return generated

    # ─────────────────────────────────────────────────────────────────────────
    # LLM Codegen
    # ─────────────────────────────────────────────────────────────────────────

    def _call_llm(self, command: str, context: str, attempt: int) -> str | None:
        prompt = textwrap.dedent(f"""
            You are an expert Python developer building plugins for JARVIS, a voice assistant.

            Write a JARVIS skill module for the command: "{command}"
            {"Context / error seen: " + context if context else ""}

            Rules:
            1. The module must define: SKILL_NAME (str), TRIGGERS (list[str]), DESCRIPTION (str), run(command, context) -> str
            2. TRIGGERS must include 2-4 keyword phrases a user might say
            3. run() must return a plain string response
            4. Use only stdlib or these safe imports: os, subprocess, datetime, re, json, requests
            5. Handle all exceptions — never raise
            6. Keep it under 60 lines
            7. Return ONLY the Python code, no markdown, no ``` blocks

            Example structure:
            SKILL_NAME  = "my_skill"
            TRIGGERS    = ["do the thing", "start the thing"]
            DESCRIPTION = "Does the thing when asked"

            def run(command: str, context: dict) -> str:
                try:
                    return "Done!"
                except Exception as e:
                    return f"Error: {{e}}"
        """).strip()

        try:
            resp = requests.post(
                OLLAMA_URL,
                json={
                    "model": FACTORY_MODEL,
                    "messages": [{"role": "user", "content": prompt}],
                    "stream": False,
                    "options": {"temperature": 0.2 if attempt == 1 else 0.5, "num_predict": 800}
                },
                timeout=60
            )
            if resp.status_code == 200:
                raw = resp.json().get("message", {}).get("content", "").strip()
                # Strip markdown code fences if LLM added them anyway
                raw = re.sub(r"^```python\s*", "", raw, flags=re.MULTILINE)
                raw = re.sub(r"^```\s*$",      "", raw, flags=re.MULTILINE)
                return raw.strip()
        except Exception as e:
            log.warning(f"[SkillFactory] LLM error: {e}")
        return None

    # ─────────────────────────────────────────────────────────────────────────
    # Helpers
    # ─────────────────────────────────────────────────────────────────────────

    def _slugify(self, text: str) -> str:
        s = text.lower().strip()
        s = re.sub(r"[^\w\s-]", "", s)
        s = re.sub(r"[\s_-]+", "_", s)
        return s[:40]

    def _already_generated(self, slug: str) -> bool:
        path = os.path.join(SKILLS_DIR, f"auto_{slug}.py")
        return os.path.exists(path)

    def _hot_load(self, skill_path: str):
        """Ask the PluginManager singleton to rescan and load the new skill."""
        try:
            from core.system.plugin_manager import get_plugin_manager
            pm = get_plugin_manager()
            pm.scan_and_load()
            log.info(f"[SkillFactory] Hot-loaded: {skill_path}")
        except Exception as e:
            log.warning(f"[SkillFactory] Hot-load failed: {e}")

    def _record_generated(self, slug: str, trigger: str, path: str):
        """Track generated skills so we don't regenerate duplicates."""
        records = []
        if os.path.exists(GENERATED_LOG):
            try:
                with open(GENERATED_LOG) as f:
                    records = json.load(f)
            except Exception:
                pass
        records.append({
            "ts":      datetime.datetime.now().isoformat(),
            "slug":    slug,
            "trigger": trigger,
            "path":    path,
        })
        try:
            with open(GENERATED_LOG, "w") as f:
                json.dump(records, f, indent=2)
        except Exception:
            pass


# Module singleton
_factory: SkillFactory | None = None


def get_skill_factory() -> SkillFactory:
    global _factory
    if _factory is None:
        _factory = SkillFactory()
    return _factory
