from __future__ import annotations
import textwrap
from pathlib import Path
from .common import slugify, extract_topic, write_text, create_run_dir

def build_college_work(
    root: Path,
    prompt: str,
    attempt: int = 1,
    verification_feedback: list[str] | None = None,
):
    from core.system.tool_registry import ToolResult
    lowered = prompt.lower()
    if "presentation" in lowered or "slides" in lowered:
        artifact = "presentation-outline"
        label = "presentation outline"
    elif "study" in lowered or "revision" in lowered:
        artifact = "study-plan"
        label = "study plan"
    elif "report" in lowered or "lab" in lowered:
        artifact = "report-draft"
        label = "report draft"
    else:
        artifact = "assignment-draft"
        label = "assignment draft"

    title = extract_topic(prompt, "College Task")
    slug = slugify(title)
    project_dir = create_run_dir(root / "generated" / "college", slug)
    feedback = verification_feedback or []
    review_note = ""
    if attempt > 1 and feedback:
        review_note = "\n## Verification Follow-up\n\n- " + "\n- ".join(feedback[:3]) + "\n"

    main_doc = textwrap.dedent(
        f"""\
        # {title}

        Generated by JARVIS as a {label}.

        ## Goal

        {prompt.strip()}

        ## Working Title

        {title}

        ## Suggested Structure

        1. Introduction
        2. Core concepts or background
        3. Main analysis or implementation
        4. Conclusion
        5. References or follow-up work

        ## Draft Starter

        {title} can be approached by first defining the problem clearly, then organizing the answer into short sections that build toward a final conclusion. Use this draft as a scaffold and replace each paragraph with your subject-specific material.

        ## Research Notes

        - Define the key terms your instructor expects.
        - Collect 2-3 credible references before rewriting the final version.
        - Add examples, diagrams, or citations where needed.

        ## Submission Checklist

        - Confirm the format requested by your instructor.
        - Add your name, section, and date.
        - Rewrite this draft in your own subject voice before submitting.
        {review_note}
        """
    )

    task_board = textwrap.dedent(
        f"""\
        # {title} Workflow

        ## Next Actions

        1. Review the prompt and marking criteria.
        2. Fill the draft with course-specific content.
        3. Add examples, formulas, screenshots, or references.
        4. Proofread and shorten repetitive lines.
        5. Export or submit in the required format.
        """
    )

    outputs = [
        write_text(project_dir / f"{artifact}.md", main_doc),
        write_text(project_dir / "task-checklist.md", task_board),
    ]

    return ToolResult(
        success=True,
        summary=f"Prepared a {label} for {title}.",
        outputs=outputs,
        details={"project_dir": str(project_dir), "artifact": artifact, "attempt": attempt},
    )
