from __future__ import annotations
from pathlib import Path
from .common import slugify, extract_topic, write_text, create_run_dir

def build_python_tool(
    root: Path,
    prompt: str,
    attempt: int = 1,
    verification_feedback: list[str] | None = None,
):
    from core.system.tool_registry import ToolResult
    from core.agent.runtime_executor import RuntimeExecutor
    title = extract_topic(prompt, "Automation Tool")
    slug = slugify(title)
    project_dir = create_run_dir(root / "generated" / "python-tools", slug)
    feedback = verification_feedback or []
    notes = ""
    if attempt > 1 and feedback:
        notes = "\n# Retry Notes\n# " + "\n# ".join(feedback[:3]) + "\n"

    tool_name = slug.replace("-", "_")
    script_py = f"""\
\"\"\"JARVIS-generated automation tool for: {prompt.strip()}\"\"\"

from __future__ import annotations

import argparse
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="JARVIS-generated automation helper")
    parser.add_argument("--input", default="", help="Optional input text or file path")
    parser.add_argument("--output", default="run-report.txt", help="Where to write the report")
    parser.add_argument("--dry-run", action="store_true", help="Preview the tool without writing output")
    return parser.parse_args()


def resolve_input(value: str) -> str:
    candidate = Path(value)
    if value and candidate.exists():
        return candidate.read_text(encoding="utf-8", errors="replace")
    return value or "No external input supplied."


def build_report(source_text: str) -> str:
    lines = [
        "JARVIS Automation Tool Report",
        "=" * 30,
        "Original request: {prompt.strip()}",
        "",
        "Input summary:",
        source_text[:600],
        "",
        "Suggested next actions:",
        "- Review the generated result.",
        "- Replace placeholder logic with task-specific automation.",
        "- Add file handling, API calls, or browser steps if needed.",
    ]
    return "\\n".join(lines) + "\\n"
{notes}

def main() -> int:
    args = parse_args()
    report = build_report(resolve_input(args.input))
    if args.dry_run:
        print(report)
        return 0

    target = Path(args.output)
    target.write_text(report, encoding="utf-8")
    print(f"Wrote report to {{target.resolve()}}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
"""

    readme_md = f"""\
# {title}

This Python automation scaffold was generated by JARVIS.

## Run

```powershell
python main.py --dry-run
python main.py --input "sample text"
```

## Purpose

{prompt.strip()}
"""

    executor = RuntimeExecutor(timeout=20)
    outputs = [
        write_text(project_dir / "main.py", script_py),
        write_text(project_dir / "README.md", readme_md),
    ]
    compile_result = executor.py_compile([project_dir / "main.py"], cwd=project_dir)
    if not compile_result.success:
        return ToolResult(
            success=False,
            summary="The generated Python tool did not compile.",
            outputs=outputs,
            details={"compile": compile_result.to_dict(), "project_dir": str(project_dir)},
        )

    return ToolResult(
        success=True,
        summary=f"Built a Python automation scaffold for {title}.",
        outputs=outputs,
        details={"project_dir": str(project_dir), "attempt": attempt, "compile": compile_result.to_dict()},
    )
