from __future__ import annotations
from pathlib import Path
from .common import slugify, extract_topic, write_text, create_run_dir

def build_website(
    root: Path,
    prompt: str,
    attempt: int = 1,
    verification_feedback: list[str] | None = None,
):
    from core.system.tool_registry import ToolResult
    title = extract_topic(prompt, "New Website")
    slug = slugify(title)
    project_dir = create_run_dir(root / "generated" / "websites", slug)
    is_portfolio = "portfolio" in prompt.lower()
    feedback = verification_feedback or []

    hero_title = title if is_portfolio else f"{title} Landing Page"
    hero_copy = (
        f"A polished portfolio experience for {title}, built as a launch-ready static site."
        if is_portfolio
        else f"A focused one-page website for {title} with a clear story, strong sections, and a call to action."
    )
    card_titles = (
        ["Selected Work", "About the Builder", "Ways to Connect"]
        if is_portfolio
        else ["Why It Matters", "What You Get", "How to Start"]
    )
    verification_note = ""
    if attempt > 1 and feedback:
        verification_note = (
            "<p class=\"verification-note\">"
            "Verification retry applied: " + " ".join(feedback[:2]) +
            "</p>"
        )

    index_html = f"""\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{hero_title}</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;700&family=IBM+Plex+Mono:wght@400;500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <div class="page-shell">
    <header class="hero" id="top">
      <nav class="nav">
        <div class="brand">JARVIS BUILD</div>
        <div class="nav-links">
          <a href="#highlights">Highlights</a>
          <a href="#process">Process</a>
          <a href="#contact">Contact</a>
        </div>
      </nav>

      <div class="hero-copy">
        <p class="eyebrow">Autonomous build output</p>
        <h1>{hero_title}</h1>
        <p class="lede">{hero_copy}</p>
        {verification_note}
        <div class="hero-actions">
          <a class="button button-primary" href="#contact">Start a Conversation</a>
          <a class="button button-secondary" href="#highlights">See the Sections</a>
        </div>
      </div>
    </header>

    <main>
      <section class="section grid-section" id="highlights">
        <div class="section-heading">
          <p class="eyebrow">Core Blocks</p>
          <h2>Designed to feel intentional, not generic.</h2>
        </div>
        <div class="card-grid">
          <article class="info-card">
            <h3>{card_titles[0]}</h3>
            <p>Feature a concise story, bold proof points, and clean visual rhythm so the page reads quickly.</p>
          </article>
          <article class="info-card">
            <h3>{card_titles[1]}</h3>
            <p>Use modular sections and editable copy so you can tailor the site without rebuilding the layout.</p>
          </article>
          <article class="info-card">
            <h3>{card_titles[2]}</h3>
            <p>Close with a focused contact block and a direct prompt so the next step is obvious for visitors.</p>
          </article>
        </div>
      </section>

      <section class="section split-section" id="process">
        <div>
          <p class="eyebrow">Workflow</p>
          <h2>How JARVIS approached this build.</h2>
        </div>
        <ol class="process-list">
          <li>Turned the request into a project title, structure, and content direction.</li>
          <li>Generated a responsive HTML, CSS, and JS starter with an opinionated visual style.</li>
          <li>Prepared the project so you can open it locally and continue iterating fast.</li>
        </ol>
      </section>

      <section class="section contact-section" id="contact">
        <p class="eyebrow">Next Step</p>
        <h2>Customize the copy, swap in your content, and launch.</h2>
        <p>Edit the text, add real images or project links, and open <code>index.html</code> to review the site locally.</p>
      </section>
    </main>

    <footer class="footer">
      <span>Generated by JARVIS autonomous workflow.</span>
      <span id="year"></span>
    </footer>
  </div>
  <script src="script.js"></script>
</body>
</html>
"""

    styles_css = """\
:root {
  --bg: #f5efe4;
  --surface: rgba(255, 252, 246, 0.84);
  --ink: #1f2a2e;
  --accent: #0f766e;
  --accent-strong: #c96f2d;
  --line: rgba(31, 42, 46, 0.12);
  --shadow: 0 20px 60px rgba(31, 42, 46, 0.12);
}

* {
  box-sizing: border-box;
}

html {
  scroll-behavior: smooth;
}

body {
  margin: 0;
  font-family: "Space Grotesk", sans-serif;
  color: var(--ink);
  background:
    radial-gradient(circle at top left, rgba(15, 118, 110, 0.15), transparent 32%),
    radial-gradient(circle at bottom right, rgba(201, 111, 45, 0.18), transparent 26%),
    linear-gradient(135deg, #f8f1e6 0%, #efe4d3 45%, #f5efe4 100%);
}

.page-shell {
  width: min(1100px, calc(100% - 32px));
  margin: 0 auto;
  padding: 24px 0 48px;
}

.hero,
.section,
.footer {
  border: 1px solid var(--line);
  background: var(--surface);
  backdrop-filter: blur(10px);
  box-shadow: var(--shadow);
}

.hero {
  padding: 28px;
  border-radius: 28px;
  overflow: hidden;
}

.nav,
.footer {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
}

.nav-links,
.hero-actions,
.card-grid {
  display: flex;
  gap: 16px;
  flex-wrap: wrap;
}

.brand,
.eyebrow,
code,
.process-list li::marker {
  font-family: "IBM Plex Mono", monospace;
}

.brand,
.eyebrow {
  text-transform: uppercase;
  letter-spacing: 0.14em;
  font-size: 0.78rem;
}

.hero-copy {
  padding: 84px 0 36px;
  max-width: 720px;
}

h1,
h2,
h3,
p {
  margin-top: 0;
}

h1 {
  font-size: clamp(3rem, 8vw, 5.6rem);
  line-height: 0.96;
  margin-bottom: 18px;
}

.lede {
  font-size: 1.1rem;
  line-height: 1.7;
  max-width: 58ch;
}

.verification-note {
  margin-bottom: 20px;
  padding: 12px 14px;
  border-left: 3px solid var(--accent-strong);
  background: rgba(201, 111, 45, 0.08);
}

.button {
  padding: 14px 20px;
  border-radius: 999px;
  text-decoration: none;
  border: 1px solid var(--ink);
  color: inherit;
}

.button-primary {
  background: var(--ink);
  color: #fff8ef;
}

.button-secondary {
  background: transparent;
}

.section {
  margin-top: 24px;
  padding: 28px;
  border-radius: 24px;
}

.grid-section .card-grid {
  margin-top: 24px;
}

.info-card {
  flex: 1 1 220px;
  min-height: 190px;
  padding: 20px;
  border-radius: 18px;
  background: rgba(255, 255, 255, 0.56);
  border: 1px solid rgba(31, 42, 46, 0.08);
}

.split-section {
  display: grid;
  grid-template-columns: 1.1fr 1fr;
  gap: 24px;
}

.process-list {
  margin: 0;
  padding-left: 20px;
  line-height: 1.9;
}

.contact-section p {
  max-width: 56ch;
}

.footer {
  margin-top: 24px;
  padding: 18px 24px;
  border-radius: 20px;
  font-size: 0.95rem;
}

a {
  color: inherit;
}

@media (max-width: 780px) {
  .page-shell {
    width: min(100% - 20px, 100%);
    padding-top: 12px;
  }

  .hero,
  .section,
  .footer {
    border-radius: 20px;
  }

  .hero-copy {
    padding-top: 48px;
  }

  .split-section {
    grid-template-columns: 1fr;
  }

  .nav,
  .footer {
    flex-direction: column;
    align-items: flex-start;
  }
}
"""

    script_js = """\
document.getElementById("year").textContent = new Date().getFullYear();
"""

    readme_md = f"""\
# {hero_title}

This website starter was generated by JARVIS.

## Files

- `index.html`: main page structure
- `styles.css`: visual styling
- `script.js`: small behavior helpers

## Run

Open `index.html` in a browser, then edit the copy and links to match your real project.
"""

    outputs = [
        write_text(project_dir / "index.html", index_html),
        write_text(project_dir / "styles.css", styles_css),
        write_text(project_dir / "script.js", script_js),
        write_text(project_dir / "README.md", readme_md),
    ]

    return ToolResult(
        success=True,
        summary=f"Built a local website starter for {title}.",
        outputs=outputs,
        details={"project_dir": str(project_dir), "attempt": attempt},
    )
