# core/architecture/protocols.py
"""
Protocol interfaces for architecture enforcement.
Defines clean contracts between modules, prevents executor coupling.
"""
from typing import Any, Callable, Optional, Protocol, runtime_checkable


@runtime_checkable
class ExecutorProtocol(Protocol):
    """Protocol for all executors."""
    def execute(self, action: Any) -> Any: ...
    def can_handle(self, action_type: str) -> bool: ...


@runtime_checkable
class RouterProtocol(Protocol):
    """Protocol for intent routers."""
    def route(self, text: str) -> tuple[Any, bool]: ...
    def cache_stats(self) -> dict: ...


@runtime_checkable
class CacheProtocol(Protocol):
    """Protocol for cache implementations."""
    def get(self, key: str) -> Any: ...
    def put(self, key: str, value: Any, confidence: float = 1.0) -> None: ...
    def stats(self) -> dict: ...
    def clear(self) -> None: ...


@runtime_checkable
class SafetyProtocol(Protocol):
    """Protocol for safety validators."""
    def validate_path(self, path: str) -> bool: ...
    def validate_shell_command(self, command: str) -> bool: ...
    def check_permission(self, path: str, operation: str) -> tuple[bool, str]: ...


@runtime_checkable
class IntentScorerProtocol(Protocol):
    """Protocol for intent scoring."""
    def score(self, text: str) -> list[Any]: ...
    def best_intent(self, text: str) -> Optional[Any]: ...


@runtime_checkable
class PlatformAdapterProtocol(Protocol):
    """Protocol for platform adapters."""
    def is_process_running(self, name: str) -> bool: ...
    def get_volume(self) -> float: ...
    def set_volume(self, level: float) -> bool: ...
    def get_gpu_info(self) -> dict: ...
    def get_cpu_usage(self) -> float: ...
    def get_ram_usage(self) -> dict: ...
